name: CD Pipeline

on:
  workflow_run:
    workflows: [ "CI Pipeline" ]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: pull docker image
        run:  docker pull marjunr/recruiter-jobsservice
      - name: delete old docker image
        run:  docker rm -f jobs-service || true
      - name: run docker container
        run:  docker run -d -p 8084:8084 --name jobs-service --network recruiter-net marjunr/recruiter-jobsservice
